/*
 * grafos.java
 *
 * 
 */
import java.awt.*;

/**
 *
 * @author Alejandro
 */

public class grafos extends javax.swing.JFrame {
  
    pincel2 lienzo2;
    pincel  lienzo;
    int x;
    /** Creates new form grafos */

    public grafos() {
        initComponents();


        lienzo2 = new pincel2(this);
        lienzo2.setBackground(new java.awt.Color(0,5,255));
        getContentPane().add(lienzo2);

        lienzo = new pincel(this);
        lienzo.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lienzo);
   }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JScrollBar();
        c1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        rb1.setText("Cuadrada");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(440, 40, 90, 23);

        rb2.setText("Sierra");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(440, 80, 80, 23);

        b1.setMaximum(5);
        b1.setMinimum(1);
        b1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        b1.setVisibleAmount(0);
        b1.setMaximumSize(new java.awt.Dimension(32767, 18));
        b1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                b1AdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(30, 370, 400, 20);

        c1.setText("1");
        getContentPane().add(c1);
        c1.setBounds(70, 340, 330, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-587)/2, (screenSize.height-449)/2, 587, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
if(rb1.isSelected()){
    b1.setValue(0);
    rb2.setSelected(false);
    lienzo.setBounds(30,20,400,300);
int a1=0 , b1=50,c1=50,d1=100, e1=100,f1=150,g1=150,h1=200, i1=200,j1=250, k1=250,l1=300, m1=300,n1=350,o1=350,a2=50 , b2=50,c2=100,d2=100, e2=150,f2=150,g2=200,h2=200, i2=250,j2=250, k2=300,l2=300, m2=350,n2=350,o2=400;
lienzo2.setVisible(false);
    this.lienzo.repintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo.repaint();

}
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
if(rb2.isSelected()){
    b1.setValue(0);
   lienzo2.setVisible(true);
    lienzo2.setBounds(30,20,400,300);
    rb1.setSelected(false);
    
   int a1=0 , b1=50,c1=50,d1=100, e1=100,f1=150,g1=150,h1=200, i1=200,j1=250, k1=250,l1=300, m1=300,n1=350,o1=350,a2=50 , b2=50,c2=100,d2=100, e2=150,f2=150,g2=200,h2=200, i2=250,j2=250, k2=300,l2=300, m2=350,n2=350,o2=400;

    this.lienzo2.rrepintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo2.repaint();
}
    }//GEN-LAST:event_rb2ActionPerformed

    private void b1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_b1AdjustmentValueChanged
x=b1.getValue();
c1.setText(String.valueOf(x));

  if(x==1){
      int a1=0 , b1=50,c1=50,d1=100, e1=100,f1=150,g1=150,h1=200, i1=200,j1=250, k1=250,l1=300, m1=300,n1=350,o1=350,
          a2=50 , b2=50,c2=100,d2=100, e2=150,f2=150,g2=200,h2=200, i2=250,j2=250, k2=300,l2=300, m2=350,n2=350,o2=400;

if(rb1.isSelected()){
            
    this.lienzo.repintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo.repaint();
      }
if(rb2.isSelected()){
    this.lienzo2.rrepintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo2.repaint();
}
}
  if(x==2){
   
int a1=-30 , b1=20,c1=20 ,d1=80, e1=80,f1=140,g1=140,h1=200, i1=200,j1=260, k1=260,l1=320, m1=320,n1=380,o1=380,
    a2=20, b2=20,c2=80,d2=80, e2=140,f2=140,g2=200,h2=200, i2=260,j2=260, k2=320,l2=320, m2=380,n2=380,o2=440;

if(rb1.isSelected()){

    this.lienzo.repintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo.repaint();
      }
if(rb2.isSelected()){

    this.lienzo2.rrepintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo2.repaint();
}   
}
 if(x==3){

int a1=-30 , b1=-20,c1=-20 ,d1=50, e1=50,f1=130,g1=130,h1=200, i1=200,j1=270, k1=270,l1=340, m1=340,n1=410,o1=410,
    a2=-20, b2=-20,c2=50,d2=50, e2=130,f2=130,g2=200,h2=200, i2=270,j2=270, k2=340,l2=340, m2=410,n2=410,o2=440;
if(rb1.isSelected()){

    this.lienzo.repintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo.repaint();
      }
if(rb2.isSelected()){
    this.lienzo2.rrepintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo2.repaint();
}
}
if(x==4){
     
int a1=-30 , b1=-20,c1=-20 ,d1=30, e1=30,f1=120,g1=120,h1=200, i1=200,j1=280, k1=280,l1=360, m1=360,n1=410,o1=410,
    a2=-20, b2=-20,c2=30,d2=30, e2=120,f2=120,g2=200,h2=200, i2=280,j2=280, k2=360,l2=360, m2=410,n2=410,o2=440;
if(rb1.isSelected()){

    this.lienzo.repintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo.repaint();
      }
if(rb2.isSelected()){
    this.lienzo2.rrepintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo2.repaint();
}
   }
  if(x==5){

int a1=-30 , b1=-20,c1=-20 ,d1=10, e1=10,f1=110,g1=110,h1=200, i1=200,j1=290, k1=290,l1=380, m1=380,n1=410,o1=410,
    a2=-20, b2=-20,c2=10,d2=10, e2=110,f2=110,g2=200,h2=200, i2=290,j2=290, k2=380,l2=380, m2=410,n2=410,o2=440;
if(rb1.isSelected()){

    this.lienzo.repintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo.repaint();
      }
if(rb2.isSelected()){
    this.lienzo2.rrepintar(a1 , b1,c1,d1, e1,f1,g1,h1, i1,j1, k1,l1, m1,n1,o1,a2 , b2,c2,d2, e2,f2,g2,h2, i2,j2, k2,l2, m2,n2,o2);
    this.lienzo2.repaint();
}
   }
    }//GEN-LAST:event_b1AdjustmentValueChanged


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafos().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar b1;
    private javax.swing.JTextField c1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    // End of variables declaration//GEN-END:variables
    
}
